apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:2dtQgyt0c3hAez/kkaBVbEdyU8bYe4yP5zNl+3dpIgDPhduloBikGLZAVZCh8d1YHril2Gi0Rof+x/OC4hyGEu27Pp97amkqd9oMNhXJOMPSlGxsoh9PAYuGNq99W6QF+DpHBHsyFJERv9zrunXFo0wg6piAY8Y5iD4Fz/1Puv27tKYablB5bhb1wQqsfsEqYhC/w8TLo6Z8/Vr+dQ2Ek+EKf2xQnjqqPdwTdNtLa7mkLbZBn0E3fK2kbTauZzyxsdV0R6kBi38HFNB/lp9BgCPGW2yBsmjVoeCKWQPvFhSJ1GFfwzkswSkJ2gU=,iv:r+T3SSHAr3y6MR+4nUjEW4TcLrWW2EPZgGU0edw/qlI=,tag:VBruk3+pr1+ddHBMO1j7Iw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age18c5hafwh6p6937ezehgjgjy5xjwsd7z69t8dgxfmzc0argtvgy8q5x4jaf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMDB5Zi9oSU54WDBxU2hx
            NTF4b25xSEMxL0Rmd2piRlR1TnoxaVFIVmo0Cko0TC9JSHdQazFiRGIxN3VLZlVj
            L0htSi9qU3NsVlFJbmYvbXhtQUx3eXcKLS0tIG5TS0c2MkVEY2lsRUltNWIyam8r
            Qk1Fb0V3L2dKTkdTcHFzMjZRWjJSNTAKEPTbFmfjX2OIrGkDQqtkWTf89DSN8SSa
            wPWDM9yCadn/A9F0mlvcQCdkpvMav5k/R95c9e4kq6J0uCR8pRjMfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T23:01:52Z"
    mac: ENC[AES256_GCM,data:OzP2cdYRw6Af+pFUzgcnYeEky7XEr2CCAFOZ5QDgzXpL/tMqbOTcQMbwcFIXkHPprzXKiR298Sofb6SD2IGDXM7nr7rdeB1b64FQoKjm7Tlm967+MNuLmQvs5Cjzaa7SIvrJbwTo8Q/Zxt8vGkv5OJHUWald+swJD1WKZ7OvjxQ=,iv:mgWJRCYtKezny3pqIiyE8+eglX4I6hAul2iKjiWvTqY=,tag:xkb9r1MYIkYLOyUdeh4B9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
