apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
          volumeMounts:
            - name: audiobooks-vol
              mountPath: /audiobooks
            - name: podcasts-vol
              mountPath: /podcasts
            - name: config-vol
              mountPath: /config
            - name: metadata-vol
              mountPath: /metadata
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: audiobooks-vol
          persistentVolumeClaim:
            claimName: audiobooks-pvc
        - name: podcasts-vol
          persistentVolumeClaim:
            claimName: podcasts-pvc
        - name: config-vol
          persistentVolumeClaim:
            claimName: config-pvc
        - name: metadata-vol
          persistentVolumeClaim:
            claimName: metadata-pvc
