apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:QHCcUCHKe4Lkme6bhaGccdqElPXPZi0z7iYnL8Tu/cVMA2GmkhKq2guc9Fuh70hSwJ1CvZeV8sI5sIrrn3m43ad+Y2vVSbQLO6O6FG/2PhFIM5PF3EgB3mzgQhphTHl9JV4RUILJQ/TUbdYPg0wxJYUkBB8GNEXkOZw0PzctmvxrtwJnieOuMPiLJFw0LIpM90KfiLAsgYHhLp8wgI8gonpBzvkQK05LuRFVh5GuLjpA5L83FXi+MhFRI2uf03G46szgiYbs1DukCMFw54W+ngTlwkH+YJkjeDb903YzvuQjs2z/dhSwZjxUVqU=,iv:Yvv4j5ClY7PQXXJ3eS2kR39XbkU97Qbs/cP/d8Enhj8=,tag:ueet1EXqWSfB3YALdKtulA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age18c5hafwh6p6937ezehgjgjy5xjwsd7z69t8dgxfmzc0argtvgy8q5x4jaf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSjljOHNyOHZReWZRaUgy
            WHIvQnFRTDZYcVZsR0pqT3ljdU1HQkV1VEFVCk1EZWFGMzQybFl4YWFvQ0FYQk93
            QjZIc2FQZlFrb0tMM1RkUmRVaW16WTgKLS0tICtiWGthV0toMUV6TTFQcmhaRm94
            QlVDYysrak5MY3VTUzgyT3pidDJFS3MKA2wsiqd97acGRMBFmFzB7nxc2q8yCTUo
            UnO9Bwt7xL/94djdoxIyD3oaQwMXTtmIaxK9yVCjg3sDbCUPMozfxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T02:39:58Z"
    mac: ENC[AES256_GCM,data:Dy8lVyr+8/C1DaNos9WLqaPdA0R5vH042U/stVTk0G4X6YgVIrDgKqqLUi7YUSTUg0j1vCT4x7t2U+IKBNWhNayM1velsz+WNnpXczREDYN5tEd6KWYMj9fXR9mpqQkimPnGK28vfipV26RQLPkpCypEAfhYS2NANsFdKepomWM=,iv:WBpkb2pf5tIpw/SugSSaNz0dgQv/8nP3sg+ID2jGCqQ=,tag:2iXRxxmamW2icMCS/PqeoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
