apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:otwv5NP/u8c=,iv:2KpgXuQOuJtcvUtC6jODIQ/lBnvZ84Z8AI8IB7OZ2jU=,tag:1roumdEVwd6cgnB2PN8jjA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:4JSJ4MjKpjb+VA2MO9NjikOsFBA=,iv:XiMGuXKWC5wN5pz7AQqbUu3COZSdOSMDSAYEpyCBOtE=,tag:YPROjhjM8QKMbecmh/AVpQ==,type:str]
kind: Secret
metadata:
    name: linkding-superuser-creds
sops:
    age:
        - recipient: age18c5hafwh6p6937ezehgjgjy5xjwsd7z69t8dgxfmzc0argtvgy8q5x4jaf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWldNcmFLMFZRdjdsbVZU
            ZFlhT1BqK1JocUNLNUVIdjd2WFl5dDN1V25vCjdpZ3R3MFFuK3NhcGZMd2l4OGQ0
            SDBHRm93ci8vdHhhMG1Iblp2UFBrZXcKLS0tIExHNUpZbkw4eE5jRllmbWFWaW9I
            TGJkd2ZqeW0xZFR1cG9UZFBYWG5heGcKUeq48WUscK+Ka6p5Ilx18a78039azTHX
            gZnybBNY4LVAeET/r0CwAw7t6E47khpHixoKpczsuKRWByHCgQty4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T02:56:13Z"
    mac: ENC[AES256_GCM,data:viNNUwl9Np/DYfEO70gXUhoYevAfmaXouPzP3XH94fDjsFytmwEjdoHDA0Mg71RN3mDTerDLd9PyT0jGM+9G48CxJIkCk/WAwf7j3P2K8XANSllvbnADxNClualHx0MqDPGelv2ND/9SklHOoOL8VbRRM94bHwD9cUi+5hFkLA4=,iv:h0BaUDb/PV719vh6ou2M7pmqXgmS+01gB813IwGIgCI=,tag:Z8vriTFW76SXlfnPUsPA1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
