apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
data:
    credentials.json: ENC[AES256_GCM,data:ir4dqTStKHo64xajmlgMLgK2lWzoPS4xQtabeSBTz/ZTqty/p0U2Xoy+LpzS4vgi8w3fy7wLYNiEynstsDKEgjIeEV0C1NGRHeiGmxmE/TKcK9ktOxG5UZGoVUsAb/0ctQvO/29K0CMYChBlBQPfJ7lBoUSmUAMUazR56WejlWYEizqmfhf2zPt2PEuyvyoUxthLbAOy8ITUAhbt/3h94sEgGxVBBtGrpHdcSSA/n3zSAf736sP5y8gSWimRRg8NzJdgbqCIaYLWi/61fPoWdBMjGxDw3TrAdgMJFrnMv5/DVzOG1acxeUdfMwg=,iv:G6zfl3YqfvIbkP8gIiMGki83TskT4jM16kDk0HrDPKE=,tag:CHmmlr2CjTZtz92zso0ldQ==,type:str]
sops:
    age:
        - recipient: age18c5hafwh6p6937ezehgjgjy5xjwsd7z69t8dgxfmzc0argtvgy8q5x4jaf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c3lGUWdvMFJRVDVWT3hH
            SW8yVnVXQW9IY0ZkeDA0WnZ4elJYYzk0aERZCmk3NzZmNThBQURTWGRGR2k2KzMw
            WS9sVWVBQmVhSnBmS25RNTAxdzh3MEEKLS0tIDkyZ0lTVWIxK1JXL09oMUdwMEor
            UFhYRGlDUy9qSy9HaVcxdkVtelJNWEUKc74JxAJjmmOODvqftsJqGqRs1uoKYs3I
            s1mv7sbjFUvEegqsFsLMF8tXr+5bThWu6TPwQpLn5VwWdSQgzbATbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T16:55:44Z"
    mac: ENC[AES256_GCM,data:B3EPdmpUb7phSxgShEtVwbM3epCUGyc0yxwtlS/vuGbYWJEaVazJEJVdldIJ4NDqnDs/jQeNQU2VhdjdVExNxYppJaWB3TQHwvoGSfMQCcp8TarfLEeBsA7ImD3hLT9KR1MggDrDNhFEtTuhq1US4T0HnvMekVtPUShebl6omec=,iv:o3N+LKPi19sHUN2Oo/atLZfnIzxmSMDcKGM9JmoK2Os=,tag:k0f06hj8ZKLQCcKo9zKAlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
