apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:jtIQevBF03BMSU+5ZkGyAmU/ltCz+0cXcznuOCXzXflAtCvob9QeLcXSTk7WwRCL/QeZFOoEvkSTKGorWCWialU52wgWvBimyJMIo3dUpPRbEU0kDqVtfnI8DAiR2qTPL23PBKyfUdkEQC1imN44y3NvXLvaHXw5vGNxOVIqEdeqOSvjBsp6WelxCf5J048XJe1Rx9VCi0afQ93Iicfz3qkbn0utZag3doYfJND65xo1TUSeylO40PZvMfhw02Os6iytw0dlbolUEJJHHoli8gAw5XTxqjZ0hlLnKdgpljIp476NIP+GlwZrdpI=,iv:5j+qpQSonebzjFbiVuHC70YPm7O4jUlnwbc9D5URy7Q=,tag:mC6n3oiPt7BUzsOUtE8Phg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age18c5hafwh6p6937ezehgjgjy5xjwsd7z69t8dgxfmzc0argtvgy8q5x4jaf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZzNaRVNTaGxHcy9lLzNh
            a05kRzJnd3F6RlB3Wkt4b3VLWXZKUVowa2hNCjN5NGhBMlR3azkzcmhDRk8rdjl4
            aTFiNElGKzFkQVlPWmhrR01DRnY0UjgKLS0tIHlhV3dDOFZZVjZtMlorbkhJd3Ix
            TldSS0NOQmFPcGc5T0Z1K2VUMzlFM00KcKdFpCRKDrHkgB14yEdGQjVG6efWvoLi
            wNaApqRTQeEHE8KprPUyzK9OPQgnNlsnogxehX77mrX6T+P+ZAhQ8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T16:09:12Z"
    mac: ENC[AES256_GCM,data:LcqxctUz8hxuiXXidpD6fHZinBw4e5F/JrjmpK76qzmKyoczc64NnCuadZlIh8/GMjkqAsE1uFWQHEWu0DKlYgdV/3OPykcECM6mV5vnA/D71LP8PtECbwyrM3qG2XfnXsowLHkoEUiYF4yeSHKjNlICE3ttlUKKEU08NHU+OoA=,iv:CDALEtcJ89ff9Oy2/77u+hy/znjOsLsVQK8XT2XW67E=,tag:YrRTal8d51hDq1Ayghhs6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
