apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:vq9SDwdFBzpP2lY2cUi37tjCTrdqrMQsDiSQ854N5O02eu5AVkd9XwjtalIrrXtdU4XVTcELZDX53IuCCar5eupIntIyqZo+TLn6v+nXlZI18+QLzWKdcOBusPkVIcSEhvzNw/L4rowxm291FSCknw+YRtmbFZBGHt0VTkbPp0RYXAwJF7hcZu2PsxqEa7ziHqM3kqNLUO4Ueb7ey5xD68Sd4MkyzGEXTknSHi45ZNIL0X6Ek6bKnKNxp0ALxl9ihCCa0gWAa2dINpXSVWCu7Gb+oDoDe5eo5QSPfAXQlRkClhdqlm9MgWzeQoCmnwEuznXkXtOtYb8=,iv:JGgpJ/UCBiGKF1MtWIa/Qmwda4VOZline7MXLA9Vcc8=,tag:ZyjQZf31YjLXnwMuQLAouw==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age18c5hafwh6p6937ezehgjgjy5xjwsd7z69t8dgxfmzc0argtvgy8q5x4jaf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtT1c5OHhLeUM4eWJxZnJt
            TXUwQm1wdUs4U0YxVGl6ekN3cHl0aGRxcjBVCnlrWHZlREZiTS9ld2g4eWVXSDEw
            Wi9hc1pXblhqc2t2bWs4ckZDcXpqeVEKLS0tIFN0cVhyMm9FVGx1YnhlenBOS2NV
            OC9SaFNGdDMvYm90UXpBMERmMHRDK3MKF5PA4eTNlrnhGQ1XSQD2QnUbirAGdZJX
            MLBYLQ/36d3p00NTQZ7uTgSBzblJVbK5spjHraM/XZ44RLgu/bNdGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T16:09:12Z"
    mac: ENC[AES256_GCM,data:LlH0gsQ7yQoExeVskYhUrqg56rqtz5iiC2OK1pupOuUJhkpUgMCy/A3mMwD3CfVMRRCvCbX2FZt5OoixEcOn77/EEo8jv1FkGxHEdxFEAISPnh1HjDkP9BuY3xp7DUvxhjgatraBOMNIJLikPr1TFI0thhaj3E+l8MVbMhQU+Nc=,iv:dAZLNGra7oBGhLAm0LKRouYkfRLHLSPMN7LY7x3P//M=,tag:nbJesV1rxC6UoTZnpkqVJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
