apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:i/4lKlvenF1C8O8YadKO3vX+3p95pxg3DuScLt4iwNjYtvtwWVXBB6HgbGkTNoh2z3y+dreJv+OismrRSBaVy6xh0kjQXnVT3JqQpgrcmXY4MNLk+CxKvad3rp6jWy4T7xVjc/uqrGEbwiFOQHGbyOFHGfDcFi3QY7JTw8IeOC9B47XKMxOBXFzT89DMWKj6AFZXHvcJAczHPaeP13KeY1ZaZc5NNtoWX2WJWbz9IXBYTBTH1mohfgSYqAgvBhfsN3C74dDIOdIt5fZZ2Ac5TMgLYIHJIQsTYVUNOGp/oV8gwzwYXCGk1m3+fuKsbutJ9QTFHLoCYJ8=,iv:f55IbXEE8cYy0kGKkfgR5TcTQ6yXyNAoWEG+XG9KGfc=,tag:hW0iPrVl8yS8sFVrHIJ/sA==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age18c5hafwh6p6937ezehgjgjy5xjwsd7z69t8dgxfmzc0argtvgy8q5x4jaf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSm5pUFJOZmF5RG9CdElu
            TUFuUVBYbVpmRTA0N1JScmNDQ3pYblRPR0RnClp5cy9kMTJUZjUwSEpuNHJYYlFE
            aytFYXJ6MFNaZnBMV3RuRzMxUUNlUlkKLS0tIFNUSytJQmtDOHNqNkxJV0Vobk1J
            ckVQazBtdE5WcGRYSytkVGsyNmwyU0kKMpwkvpSfY2iGEL97cajH2PAAYS1ySWSd
            hh93c2rBI6iFvqzHjSMzfICvBgtYfFQIB2TQ85N9fnVzk+W43WzLcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T16:23:39Z"
    mac: ENC[AES256_GCM,data:WFu10he4QyWg/J3vJyuWYhm7/cfN/m1ZLKtP18UO1Ok0tGSYOjQ6HdNfOZgZD4zpm6klm756NGLUWRSapTzi+WnqDok4JuuSK11jH277SJ28Ai3BxhbLkKfRV8DvTUSSoFgCBjf8jf7ZCurhaU81D3nuN39HSarOYWCjxh1922I=,iv:EOiD+8jhfvK1HaGVDcbaXnbnGTCd1B8KFxQQYGNF1rw=,tag:NzwjzGvVpIxilEQn6dT0iA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
