apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
      containers:
        - name: linkding
          image: ghcr.io/sissbruecker/linkding:1.45.0
          env:
            - name: LD_SUPERUSER_NAME
              secretKeyRef:
                - name: linkding-superuser-creds
                  key: LD_SUPERUSER_NAME
            - name: LD_SUPERUSER_NAME
              secretKeyRef:
                - name: linkding-superuser-creds
                  key: LD_SUPERUSER_PASSWORD
          ports:
            - containerPort: 9090
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: "/etc/linkding/data"
              name: linkding-data
